---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: openrewrite/gh-automation/.github/workflows/ci-gradle-blacksmith.yml@main
    with:
      runs_on: blacksmith-4vcpu-ubuntu-2404
      java_version: |
        25
        21
      rerun_tasks: true
    secrets:
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype_token: ${{ secrets.SONATYPE_TOKEN}}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      OPS_GITHUB_ACTIONS_WEBHOOK: ${{ secrets.OPS_GITHUB_ACTIONS_WEBHOOK }}
      node_auth_token: ${{ secrets.NPM_TOKEN }}
      pypi_token: ${{ secrets.PYPI_OPENREWRITE_PUBLISH }}
