---
name: moderne-ingest

on:
  push:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ingest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ingest:
    uses: openrewrite/gh-automation/.github/workflows/moderne-ingest.yml@main
    secrets:
      moderne_api_access_token: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
