---
name: nightly-ci

on:
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: openrewrite/gh-automation/.github/workflows/ci-gradle.yml@main
    with:
      java_version: |
        25
        21
    secrets:
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype_token: ${{ secrets.SONATYPE_TOKEN}}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      OPS_GITHUB_ACTIONS_WEBHOOK: ${{ secrets.OPS_GITHUB_ACTIONS_WEBHOOK }}
      node_auth_token: ${{ secrets.NPM_TOKEN }}
